apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${ENVIRONMENT}

resources:
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - service-accounts.yaml
  - secrets.yaml
  - configmap.yaml

commonLabels:
  environment: ${ENVIRONMENT}
  app.kubernetes.io/part-of: ecommerce

configMapGenerator:
  - name: app-config
    behavior: merge
    envs:
      - .env

secretGenerator:
  - name: backend-secrets
    behavior: merge
    envs:
      - .env.secrets

vars:
  - name: ENVIRONMENT
    objref:
      kind: ConfigMap
      name: app-config
      apiVersion: v1
    fieldref:
      fieldpath: data.ENVIRONMENT
  - name: AWS_REGION
    objref:
      kind: ConfigMap
      name: app-config
      apiVersion: v1
    fieldref:
      fieldpath: data.AWS_REGION
