apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: ${ENVIRONMENT}
type: Opaque
stringData:
  database-url: "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}"
  redis-url: "redis://${REDIS_HOST}:6379"
  jwt-secret: "${JWT_SECRET}"
