apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: ${ENVIRONMENT}
  annotations:
    eks.amazonaws.com/role-arn: ${BACKEND_ROLE_ARN}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: ${ENVIRONMENT}
  annotations:
    eks.amazonaws.com/role-arn: ${FRONTEND_ROLE_ARN}
